name: Django CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linter
        run: |
          pip install flake8
          flake8
      - name: Run tests
        run: |
          python manage.py test
